<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InfographicsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $superAdminId = DB::table('users')->select(['id', 'name'])->where('name', 'superadmin')->first()->id;
        $infografis = array(
            array(
                'id' => '12',
                'user_id' => $superAdminId,
                'title' => 'E-commerce Amazon',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum cursus arcu eget convallis venenatis. Praesent vitae neque ligula. Aliquam venenatis tempus ligula ac luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
                'slug' => 'e-commerce-amazon',
                'image' => 'uploads/infografis/E-commerce_Amazon1538034357.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '13',
                'user_id' => $superAdminId,
                'title' => 'Bahaya Rokok',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum cursus arcu eget convallis venenatis. Praesent vitae neque ligula. Aliquam venenatis tempus ligula ac luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
                'slug' => 'bahaya-rokok',
                'image' => 'uploads/infografis/Bahaya_Rokok1538034391.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '14',
                'user_id' => $superAdminId,
                'title' => 'Buah Import',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum cursus arcu eget convallis venenatis. Praesent vitae neque ligula. Aliquam venenatis tempus ligula ac luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
                'slug' => 'buah-import',
                'image' => 'uploads/infografis/Buah_Import1538034407.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '15',
                'user_id' => $superAdminId,
                'title' => 'Inflasi Kalimantan Barat',
                'description' => 'Data inflasi di Kalimantan Barat hingga Juni 2018.',
                'slug' => 'inflasi-kalimantan-barat',
                'image' => 'uploads/infografis/Inflasi_Kalimantan_Barat1539590710.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '16',
                'user_id' => $superAdminId,
                'title' => 'Insentif Pajak',
                'description' => 'Data insentif pajak di kawasan Ekonomi Khusus.',
                'slug' => 'insentif-pajak',
                'image' => 'uploads/infografis/Insentif_Pajak1539590766.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '17',
                'user_id' => $superAdminId,
                'title' => 'Konservasi Ikan',
                'description' => 'Data konservasi jenis ikan di Kalimantan tahun 2009 hingg 2016.',
                'slug' => 'konservasi-ikan',
                'image' => 'uploads/infografis/Konservasi_Ikan1539590858.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '18',
                'user_id' => $superAdminId,
                'title' => 'Paket Kebijakan Ekonomi',
                'description' => 'Data paket kebijakan ekonomi di Kawasan Ekonomi Khusus.',
                'slug' => 'paket-kebijakan-ekonomi',
                'image' => 'uploads/infografis/Paket_Kebijakan_Ekonomi1539590904.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '19',
                'user_id' => $superAdminId,
                'title' => 'Paket Kebijakan Ekonomi II',
                'description' => 'Data paket kebijakan ekonomi di Kawasan Ekonomi Khusus.',
                'slug' => 'paket-kebijakan-ekonomi-ii',
                'image' => 'uploads/infografis/Paket_Kebijakan_Ekonomi_II1539590934.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '20',
                'user_id' => $superAdminId,
                'title' => 'Paket Kebijakan Ekonomi III',
                'description' => 'Data paket kebijakan ekonomi di Kawasan Ekonomi Khusus.',
                'slug' => 'paket-kebijakan-ekonomi-iii',
                'image' => 'uploads/infografis/Paket_Kebijakan_Ekonomi_III1539590968.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '21',
                'user_id' => $superAdminId,
                'title' => 'Sistem Integritas Pontianak',
                'description' => 'Sistem Integritas dan Indeks Persepsi Korupsi di Kota Pontianak.',
                'slug' => 'sistem-integrasi-pontianak',
                'image' => 'uploads/infografis/Sistem_Integritas_Pontianak1539591032.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '22',
                'user_id' => $superAdminId,
                'title' => 'Mengenal Kalimantan Barat',
                'description' => 'Khasanah Kalimantan Barat. Taman Nasional, rumah khas, tarian, fauna, dan juga flora.',
                'slug' => 'mengenal-kalimantan-barat',
                'image' => 'uploads/infografis/Mengenal_Kalimantan_Barat1539591100.jpg',
                'created_at' => '2018-10-29 20:23:28',
                'updated_at' => '2018-10-29 20:23:28',
            ),
            array(
                'id' => '24',
                'user_id' => $superAdminId,
                'title' => 'Kalender Event Pemerintah Kota Pontianak',
                'description' => 'Agenda tahunan pemerintah kota pontianak',
                'slug' => 'kalender-event-pemerintah-kota-pontianak',
                'image' => 'uploads/infografis/Kalender_Event_Pemerintah_Kota_Pontianak1562830504.png',
                'created_at' => '2019-07-10 17:35:04',
                'updated_at' => '2019-07-10 17:35:04',
            ),
            array(
                'id' => '25',
                'user_id' => $superAdminId,
                'title' => 'Kalender Event Pemerintah Kota Pontianak I',
                'description' => 'Agenda tahunan pemerintahan kota pontianak',
                'slug' => 'kalender-event-pemerintah-kota-pontianak-i',
                'image' => 'uploads/infografis/Kalender_Event_Pemerintah_Kota_Pontianak_I1562830573.png',
                'created_at' => '2019-07-10 17:36:13',
                'updated_at' => '2019-07-10 17:36:13',
            ),
            array(
                'id' => '26',
                'user_id' => $superAdminId,
                'title' => 'Kalender Event Pemerintah Kota Pontianak II',
                'description' => 'Agenda Tahunan Kota Pontianak',
                'slug' => 'kalender-event-pemerintah-kota-pontianak-ii',
                'image' => 'uploads/infografis/Kalender_Event_Pemerintah_Kota_Pontianak_II1562830612.png',
                'created_at' => '2019-07-10 17:36:52',
                'updated_at' => '2019-07-10 17:36:52',
            ),
            array(
                'id' => '27',
                'user_id' => $superAdminId,
                'title' => 'Kalender Event Pemerintah Kota Pontianak III',
                'description' => 'Agenda tahunan pemerintahan kota pontianak',
                'slug' => 'kalender-event-pemerintah-kota-pontianak-iii',
                'image' => 'uploads/infografis/Kalender_Event_Pemerintah_Kota_Pontianak_III1562830661.png',
                'created_at' => '2019-07-10 17:37:41',
                'updated_at' => '2019-07-10 17:37:41',
            ),
            array(
                'id' => '28',
                'user_id' => $superAdminId,
                'title' => 'Kalender Event Pemerintah Kota Pontianak IV',
                'description' => 'agenda tahunan pemerintahan kota pontianak',
                'slug' => 'kalender-event-pemerintah-kota-pontianak-iv',
                'image' => 'uploads/infografis/Kalender_Event_Pemerintah_Kota_Pontianak_IV1562830692.png',
                'created_at' => '2019-07-10 17:38:12',
                'updated_at' => '2019-07-10 17:38:12',
            ),
            array(
                'id' => '29',
                'user_id' => $superAdminId,
                'title' => 'cegah covid saat bekerja',
                'description' => 'jika masih harus tetap bekerja ditengah pandemi maka harus mengikuti protokol kesehatan dan himbauan pemerintah dalam mencegah penyebaran covid-19',
                'slug' => 'cegah-covid-saat-bekerja',
                'image' => 'uploads/infografis/cegah_covid_saat_bekerja1601621426.png',
                'created_at' => '2020-10-01 16:50:26',
                'updated_at' => '2020-10-01 16:50:26',
            ),
            array(
                'id' => '30',
                'user_id' => $superAdminId,
                'title' => 'Cegah Covid Saat Bekerja',
                'description' => 'Ketika Berangkat Bekerja',
                'slug' => 'cegah-covid-saat-bekerja-1',
                'image' => 'uploads/infografis/Cegah_Covid_Saat_Bekerja1601621741.png',
                'created_at' => '2020-10-01 16:55:41',
                'updated_at' => '2020-10-01 16:55:41',
            ),
            array(
                'id' => '31',
                'user_id' => $superAdminId,
                'title' => 'Cegah Covid Saat Bekerja',
                'description' => 'Ketika Berada di Tempat Bekerja',
                'slug' => 'cegah-covid-saat-bekerja-2',
                'image' => 'uploads/infografis/Cegah_Covid_Saat_Bekerja1601621786.png',
                'created_at' => '2020-10-01 16:56:26',
                'updated_at' => '2020-10-01 16:56:26',
            ),
            array(
                'id' => '32',
                'user_id' => $superAdminId,
                'title' => 'Aplikasi Jepin',
                'description' => 'Mengenal Aplikasi Jepin',
                'slug' => 'aplikasi-jepin',
                'image' => 'uploads/infografis/Aplikasi_Jepin1601621833.png',
                'created_at' => '2020-10-01 16:57:13',
                'updated_at' => '2020-10-01 16:57:13',
            ),
            array(
                'id' => '33',
                'user_id' => $superAdminId,
                'title' => 'Aplikasi Jepin',
                'description' => 'Pengertian Aplikasi Jepin',
                'slug' => 'aplikasi-jepin-1',
                'image' => 'uploads/infografis/Aplikasi_Jepin1601621878.png',
                'created_at' => '2020-10-01 16:57:58',
                'updated_at' => '2020-10-01 16:57:58',
            ),
            array(
                'id' => '34',
                'user_id' => $superAdminId,
                'title' => 'Aplikasi Jepin',
                'description' => 'Penjelasan Aplikasi Jepin',
                'slug' => 'aplikasi-jepin-2',
                'image' => 'uploads/infografis/Aplikasi_Jepin1601621952.png',
                'created_at' => '2020-10-01 16:59:12',
                'updated_at' => '2020-10-01 16:59:12',
            ),
            array(
                'id' => '36',
                'user_id' => $superAdminId,
                'title' => 'Layanan Smart City',
                'description' => 'Layanan Smart City Pada Aplikasi Jepin',
                'slug' => 'layanan-smart-city',
                'image' => 'uploads/infografis/Layanan_Smart_City1601622404.jpg',
                'created_at' => '2020-10-01 17:06:44',
                'updated_at' => '2020-10-01 17:06:44',
            ),
            array(
                'id' => '37',
                'user_id' => $superAdminId,
                'title' => 'Layanan Smart City',
                'description' => 'Layanan Smart city di Jepin',
                'slug' => 'layanan-smart-city-1',
                'image' => 'uploads/infografis/Layanan_Smart_City1601622453.jpg',
                'created_at' => '2020-10-01 17:07:33',
                'updated_at' => '2020-10-01 17:07:33',
            ),
            array(
                'id' => '38',
                'user_id' => $superAdminId,
                'title' => 'Layanan Smart City',
                'description' => 'Layanan Smart City di Jepin',
                'slug' => 'layanan-smart-city-2',
                'image' => 'uploads/infografis/Layanan_Smart_City1601622480.jpg',
                'created_at' => '2020-10-01 17:08:00',
                'updated_at' => '2020-10-01 17:08:00',
            ),
            array(
                'id' => '39',
                'user_id' => $superAdminId,
                'title' => 'Protokol kesehatan',
                'description' => 'Infografis Cafe',
                'slug' => 'protokol-kesehatan',
                'image' => 'uploads/infografis/Protokol_kesehatan1601622544.png',
                'created_at' => '2020-10-01 17:09:04',
                'updated_at' => '2020-10-01 17:09:04',
            ),
            array(
                'id' => '40',
                'user_id' => $superAdminId,
                'title' => 'Protokol kesehatan',
                'description' => 'Infografis Restaurant',
                'slug' => 'protokol-kesehatan-1',
                'image' => 'uploads/infografis/Protokol_kesehatan1601622581.png',
                'created_at' => '2020-10-01 17:09:41',
                'updated_at' => '2020-10-01 17:09:41',
            ),
            array(
                'id' => '41',
                'user_id' => $superAdminId,
                'title' => 'Protokol kesehatan',
                'description' => 'Infografis Tempat ibadah',
                'slug' => 'protokol-kesehatan-2',
                'image' => 'uploads/infografis/Protokol_kesehatan1601622610.png',
                'created_at' => '2020-10-01 17:10:10',
                'updated_at' => '2020-10-01 17:10:10',
            ),
            array(
                'id' => '42',
                'user_id' => $superAdminId,
                'title' => 'Smart Branding',
                'description' => 'Smart branding 1',
                'slug' => 'smart-branding',
                'image' => 'uploads/infografis/Smart_Branding1601622667.jpg',
                'created_at' => '2020-10-01 17:11:07',
                'updated_at' => '2020-10-01 17:14:09',
            ),
            array(
                'id' => '43',
                'user_id' => $superAdminId,
                'title' => 'Smart Branding',
                'description' => 'Smart branding 2',
                'slug' => 'smart-branding-1',
                'image' => 'uploads/infografis/Smart_Branding1601622825.jpg',
                'created_at' => '2020-10-01 17:13:45',
                'updated_at' => '2020-10-01 17:13:45',
            ),
            array(
                'id' => '44',
                'user_id' => $superAdminId,
                'title' => 'Smart Branding',
                'description' => 'Smart Branding 3',
                'slug' => 'smart-branding-2',
                'image' => 'uploads/infografis/Smart_Branding1601622876.jpg',
                'created_at' => '2020-10-01 17:14:36',
                'updated_at' => '2020-10-01 17:14:36',
            ),
            array(
                'id' => '45',
                'user_id' => $superAdminId,
                'title' => 'Tips Ibadah Ramadhan',
                'description' => 'Tips Ibadah Ramadhan Aman Dari Covid',
                'slug' => 'tips-ibadah-ramadhan',
                'image' => 'uploads/infografis/Tips_Ibadah_Ramadhan1601622978.jpeg',
                'created_at' => '2020-10-01 17:16:18',
                'updated_at' => '2020-10-01 17:16:18',
            ),
            array(
                'id' => '46',
                'user_id' => $superAdminId,
                'title' => 'Data Terbaru Covid',
                'description' => 'Data Terbaru Covid',
                'slug' => 'data-terbaru-covid',
                'image' => 'uploads/infografis/Data_Terbaru_Covid1601623037.jpg',
                'created_at' => '2020-10-01 17:17:17',
                'updated_at' => '2020-10-01 17:17:17',
            ),
            array(
                'id' => '47',
                'user_id' => $superAdminId,
                'title' => 'Layanan Cepat Tanggap',
                'description' => 'Tenang Hadapi Covid',
                'slug' => 'layanan-cepat-tanggap',
                'image' => 'uploads/infografis/Layanan_Cepat_Tanggap1601623100.jpg',
                'created_at' => '2020-10-01 17:18:21',
                'updated_at' => '2020-10-01 17:18:21',
            ),
            array(
                'id' => '48',
                'user_id' => $superAdminId,
                'title' => 'Pakai Masker',
                'description' => 'Jangan Kendor Disiplin Pakai Masker',
                'slug' => 'pakai-masker',
                'image' => 'uploads/infografis/Pakai_Masker1601623485.jpg',
                'created_at' => '2020-10-01 17:24:46',
                'updated_at' => '2020-10-01 17:24:46',
            ),
            array(
                'id' => '49',
                'user_id' => $superAdminId,
                'title' => 'Pakai Masker',
                'description' => 'Gunakan Masker',
                'slug' => 'pakai-masker-1',
                'image' => 'uploads/infografis/Pakai_Masker1601623539.png',
                'created_at' => '2020-10-01 17:25:39',
                'updated_at' => '2020-10-01 17:25:39',
            ),
            array(
                'id' => '50',
                'user_id' => $superAdminId,
                'title' => 'Perpustakaan',
                'description' => 'Perpustakaan Kota pontianak',
                'slug' => 'perpustakaan',
                'image' => 'uploads/infografis/Perpustakaan1601623577.jpg',
                'created_at' => '2020-10-01 17:26:17',
                'updated_at' => '2020-10-01 17:26:17',
            ),
            array(
                'id' => '51',
                'user_id' => $superAdminId,
                'title' => 'Perpustakaan',
                'description' => 'Manfaat Membaca',
                'slug' => 'perpustakaan-1',
                'image' => 'uploads/infografis/Perpustakaan1601623707.jpg',
                'created_at' => '2020-10-01 17:28:27',
                'updated_at' => '2020-10-01 17:28:27',
            ),
            array(
                'id' => '52',
                'user_id' => $superAdminId,
                'title' => 'Rujukan Rumah Sakit',
                'description' => 'Rujukan Rumah Sakit',
                'slug' => 'rujukan-rumah-sakit',
                'image' => 'uploads/infografis/Rujukan_Rumah_Sakit1601623751.jpg',
                'created_at' => '2020-10-01 17:29:11',
                'updated_at' => '2020-10-01 17:29:11',
            ),
            array(
                'id' => '53',
                'user_id' => $superAdminId,
                'title' => 'Tips Belanja Online',
                'description' => 'Tips Belanja Pangan Online',
                'slug' => 'tips-belanja-online',
                'image' => 'uploads/infografis/Tips_Belanja_Online1601623788.jpg',
                'created_at' => '2020-10-01 17:29:48',
                'updated_at' => '2020-10-01 17:29:48',
            ),
            array(
                'id' => '54',
                'user_id' => $superAdminId,
                'title' => 'Tips Belanja Online',
                'description' => 'Tips Belanja Online 2',
                'slug' => 'tips-belanja-online-1',
                'image' => 'uploads/infografis/Tips_Belanja_Online1601623819.jpg',
                'created_at' => '2020-10-01 17:30:19',
                'updated_at' => '2020-10-01 17:30:19',
            ),
            array(
                'id' => '55',
                'user_id' => $superAdminId,
                'title' => 'Virus Corona',
                'description' => 'Waspada Virus Corona',
                'slug' => 'virus-corona',
                'image' => 'uploads/infografis/Virus_Corona1601623855.jpg',
                'created_at' => '2020-10-01 17:30:55',
                'updated_at' => '2020-10-01 17:30:55',
            )
        );

        DB::beginTransaction();
        try {
            DB::table('infographics')->insert($infografis);
            DB::commit();
        } catch (\Throwable $th) {
            DB::rollBack();
            throw $th;
        }
    }
}
