<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SliderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $superAdminId = DB::table('users')->select(['id', 'name'])->where('name', 'superadmin')->first()->id;
        $categoryWisataId = DB::table('slider_category')->select(['id', 'category'])->where('category', 'wisata')->first()->id;
        $categoryPenginapanId = DB::table('slider_category')->select(['id', 'category'])->where('category', 'penginapan')->first()->id;
        $categoryKulinerId = DB::table('slider_category')->select(['id', 'category'])->where('category', 'kuliner')->first()->id;
        $categoryOlehId = DB::table('slider_category')->select(['id', 'category'])->where('category', 'oleh-oleh')->first()->id;
        $categoryBerandaId = DB::table('slider_category')->select(['id', 'category'])->where('category', 'beranda')->first()->id;
        $categoryKomoditasId = DB::table('slider_category')->select(['id', 'category'])->where('category', 'komoditas')->first()->id;

        $sliders = array(
            array(
                'id' => '3',
                'user_id' => $superAdminId,
                'title' => 'Tugu Katulistiwa',
                'description' => 'Monumen Kebanggan Warga Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Tugu_Katulistiwa1690349191.jpg',
                'color' => '#b4ff3f',
                'category_id' => $categoryWisataId,
                'created_at' => '2019-06-17 02:55:44',
                'updated_at' => '2023-07-26 05:26:31',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '4',
                'user_id' => $superAdminId,
                'title' => 'Taman Alun-alun Kapuas',
                'description' => 'Air mancur menari sesual alunan musik',
                'url' => NULL,
                'image' => 'uploads/Slider/Taman_Alun-alun_Kapuas1560766285.webp',
                'color' => '#7ecca7',
                'category_id' => $categoryWisataId,
                'created_at' => '2019-06-17 03:11:26',
                'updated_at' => '2019-07-08 16:49:16',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '8',
                'user_id' => $superAdminId,
                'title' => 'Hotel Grand Mahkota',
                'description' => 'Salah Satu hotel Bintang 4 di Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Hotel_Grand_Mahkota1561386280.webp',
                'color' => '#c5d419',
                'category_id' => $categoryPenginapanId,
                'created_at' => '2019-06-24 07:24:41',
                'updated_at' => '2019-06-24 07:24:41',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '12',
                'user_id' => $superAdminId,
                'title' => 'Bingke Berendam',
                'description' => 'Kue Khas Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Bingke_Berendam1562741842.webp',
                'color' => '#000000',
                'category_id' => $categoryKulinerId,
                'created_at' => '2019-07-09 23:57:22',
                'updated_at' => '2019-07-10 00:16:15',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '17',
                'user_id' => $superAdminId,
                'title' => 'Kue Cucur',
                'description' => 'Jajanan Khas Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Kue_Cucur1562743141.webp',
                'color' => '#000000',
                'category_id' => $categoryKulinerId,
                'created_at' => '2019-07-10 00:19:03',
                'updated_at' => '2019-07-10 00:19:03',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '18',
                'user_id' => $superAdminId,
                'title' => 'Pengkang',
                'description' => 'Jajanan Khas Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Pengkang1562743219.webp',
                'color' => '#000000',
                'category_id' => $categoryKulinerId,
                'created_at' => '2019-07-10 00:20:20',
                'updated_at' => '2019-07-10 00:20:20',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '19',
                'user_id' => $superAdminId,
                'title' => 'Chai Kue',
                'description' => 'Jajanan Khas Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Chai_Kue1562743328.webp',
                'color' => '#000000',
                'category_id' => $categoryKulinerId,
                'created_at' => '2019-07-10 00:22:09',
                'updated_at' => '2019-07-10 00:22:09',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '20',
                'user_id' => $superAdminId,
                'title' => 'Hotel Orchadz',
                'description' => 'Salah Satu Hotel Bintang 3 Di Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Hotel_Orchadz1562748820.webp',
                'color' => '#000000',
                'category_id' => $categoryPenginapanId,
                'created_at' => '2019-07-10 01:53:41',
                'updated_at' => '2019-07-10 01:53:41',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '21',
                'user_id' => $superAdminId,
                'title' => 'Hotel Kapuas Palace Pontianak',
                'category_id' => $categoryPenginapanId,
                'description' => 'Salah Satu Hotel Bintang 3 Di Kota Pontianak',
                'image' => 'uploads/Slider/Hotel_Kapuas_Palace_Pontianak1562748909.webp',
                'color' => '#000000',
                'url' => NULL,
                'created_at' => '2019-07-10 01:55:11',
                'updated_at' => '2019-07-10 01:55:11',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '22',
                'user_id' => $superAdminId,
                'title' => 'Golden Tulip',
                'description' => 'Salah Satu Hotel Bintang 4 Di KOta Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Golden_Tulip1562749130.webp',
                'color' => '#000000',
                'category_id' => $categoryPenginapanId,
                'created_at' => '2019-07-10 01:58:51',
                'updated_at' => '2019-07-10 01:58:51',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '23',
                'user_id' => $superAdminId,
                'title' => 'Hotel 95',
                'description' => 'Salah Satu Hotel Bintang 2 Di Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Hotel_951562749220.webp',
                'color' => '#000000',
                'category_id' => $categoryPenginapanId,
                'created_at' => '2019-07-10 02:00:21',
                'updated_at' => '2019-07-10 02:06:59',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '24',
                'user_id' => $superAdminId,
                'title' => 'Taman Catur Untan',
                'description' => 'Tempat Rekreasi Bersama Sahabat Dan Keluarga',
                'url' => NULL,
                'image' => 'uploads/Slider/Taman_Catur_Untan1562749330.webp',
                'color' => '#000000',
                'category_id' => $categoryWisataId,
                'created_at' => '2019-07-10 02:02:11',
                'updated_at' => '2019-07-10 02:06:28',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '25',
                'user_id' => $superAdminId,
                'title' => 'Water Front',
                'description' => 'Tempat Memanjakan Mata Di Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Water_Front1562749464.webp',
                'color' => '#000000',
                'category_id' => $categoryWisataId,
                'created_at' => '2019-07-10 02:04:25',
                'updated_at' => '2019-07-10 02:05:48',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '26',
                'user_id' => $superAdminId,
                'title' => 'Joging Track Untan',
                'description' => 'Tempat Joging Dan Rekreasi Bersama Sahabat & Keluarga',
                'url' => NULL,
                'image' => 'uploads/Slider/Joging_Track_Untan1562750216.webp',
                'color' => '#000000',
                'category_id' => $categoryWisataId,
                'created_at' => '2019-07-10 02:16:57',
                'updated_at' => '2019-07-10 02:16:57',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '29',
                'user_id' => $superAdminId,
                'title' => 'Patuhi Protokol Kesehatan Dengan 4M',
                'category_id' => $categoryBerandaId,
                'description' => 'Protokol 4M',
                'image' => 'uploads/Slider/Patuhi_Protokol_Kesehatan_Dengan_4M1610440341.png',
                'color' => '#3175bf',
                'url' => NULL,
                'created_at' => '2020-09-28 13:26:11',
                'updated_at' => '2021-01-11 18:32:21',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '32',
                'user_id' => $superAdminId,
                'title' => 'Info Harga Komoditas',
                'description' => 'Info Harga Komoditas di Aplikasi Jepin',
                'url' => NULL,
                'image' => 'uploads/Slider/Info_Harga_Komoditas1610613188.jpeg',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2021-01-13 17:55:53',
                'updated_at' => '2021-01-13 18:33:08',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '33',
                'user_id' => $superAdminId,
                'title' => 'Taman Parit Nanas',
                'description' => 'Taman yang terletak di samping Tol Landak',
                'url' => NULL,
                'image' => 'uploads/Slider/Taman_Parit_Nanas1610612448.jpg',
                'color' => '#ffffff',
                'category_id' => $categoryWisataId,
                'created_at' => '2021-01-13 18:10:58',
                'updated_at' => '2021-01-13 18:20:48',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '34',
                'user_id' => $superAdminId,
                'title' => 'Taman Parit Nanas',
                'description' => 'Taman Parit Nanas',
                'url' => NULL,
                'image' => 'uploads/Slider/Taman_Parit_Nanas1610613025.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2021-01-13 18:30:26',
                'updated_at' => '2021-01-13 18:30:26',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '35',
                'user_id' => $superAdminId,
                'title' => 'Peta Wisata',
                'description' => 'Peta Wisata Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Peta_Wisata1610613245.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2021-01-13 18:34:05',
                'updated_at' => '2021-01-13 18:34:05',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '36',
                'user_id' => $superAdminId,
                'title' => 'Peta Wisata',
                'description' => 'Peta Wisata Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/Peta_Wisata1610613370.webp',
                'color' => '#ffffff',
                'category_id' => $categoryWisataId,
                'created_at' => '2021-01-13 18:36:11',
                'updated_at' => '2021-01-13 18:36:11',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '45',
                'user_id' => $superAdminId,
                'title' => 'Satu Data Kota Pontianak',
                'category_id' => $categoryBerandaId,
                'description' => '-',
                'image' => 'uploads/Slider/Satu_Data_Kota_Pontianak1647227037.webp',
                'color' => '#ffffff',
                'url' => 'https://satudata.pontianak.go.id/',
                'created_at' => '2022-03-13 20:03:58',
                'updated_at' => '2024-04-04 06:23:40',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '46',
                'user_id' => $superAdminId,
                'title' => 'SP4N - Lapor!',
                'description' => '-',
                'url' => 'https://www.lapor.go.id/',
                'image' => 'uploads/Slider/Lapor_SP4N1647227065.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2022-03-13 20:04:26',
                'updated_at' => '2022-03-23 23:45:34',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '47',
                'user_id' => $superAdminId,
                'title' => 'Aplikasi Jepin',
                'description' => 'Jendela Pontianak Integrasi',
                'url' => 'https://jepin.pontianak.go.id/',
                'image' => 'uploads/Slider/Aplikasi_Jepin1647228959.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2022-03-13 20:35:59',
                'updated_at' => '2024-04-04 06:35:10',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '48',
                'user_id' => $superAdminId,
                'title' => 'Start-up Hub Kota Pontianak',
                'description' => '-',
                'url' => 'https://startuphub.pontianak.go.id/',
                'image' => 'uploads/Slider/Start-up_Hub_Kota_Pontianak1647328791.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2022-03-15 00:19:51',
                'updated_at' => '2024-04-04 06:36:14',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '49',
                'user_id' => $superAdminId,
                'title' => 'PPID Kota Pontianak',
                'description' => '-',
                'url' => 'https://ppid.pontianak.go.id/',
                'image' => 'uploads/Slider/PPID_Kota_Pontianak1647328819.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2022-03-15 00:20:19',
                'updated_at' => '2024-04-04 06:39:11',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '58',
                'user_id' => $superAdminId,
                'title' => 'Agenda HUT Pontianak',
                'description' => '-',
                'url' => NULL,
                'image' => 'uploads/Slider/Agenda_HUT_Pontianak1697516836.webp',
                'color' => '#ffffff',
                'category_id' => $categoryBerandaId,
                'created_at' => '2023-10-17 04:27:16',
                'updated_at' => '2023-10-17 04:27:16',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '59',
                'user_id' => $superAdminId,
                'title' => 'HUT ke-252 Tahun Pontianak',
                'category_id' => $categoryBerandaId,
                'description' => '-',
                'url' => NULL,
                'image' => 'uploads/Slider/HUT_ke-252_Tahun_Pontianak1697517822.webp',
                'color' => '#ffffff',
                'created_at' => '2023-10-17 04:43:42',
                'updated_at' => '2023-10-17 04:43:42',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '61',
                'user_id' => $superAdminId,
                'title' => 'Beras Medium 1 (Cap Bunga)',
                'description' => '-',
                'url' => NULL,
                'image' => 'uploads/Slider/Beras1707267091.webp',
                'color' => '#000000',
                'category_id' => $categoryKomoditasId,
                'created_at' => '2024-02-07 00:51:31',
                'updated_at' => '2024-02-07 00:53:37',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '62',
                'user_id' => $superAdminId,
                'title' => 'Beras Khusus (Beras Merah)',
                'category_id' => $categoryKomoditasId,
                'description' => '-',
                'url' => NULL,
                'image' => 'uploads/Slider/Beras_Khusus_(Beras_Merah)1707267294.webp',
                'color' => '#000000',
                'created_at' => '2024-02-07 00:54:54',
                'updated_at' => '2024-02-07 00:54:54',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '63',
                'user_id' => $superAdminId,
                'title' => 'Kedelai Lokal',
                'description' => '-',
                'url' => NULL,
                'image' => 'uploads/Slider/Kedelai_Lokal1707267331.webp',
                'color' => '#000000',
                'category_id' => $categoryKomoditasId,
                'created_at' => '2024-02-07 00:55:31',
                'updated_at' => '2024-02-07 00:55:31',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '64',
                'user_id' => $superAdminId,
                'title' => 'PSP Pusat Oleh-Oleh',
                'description' => 'Pusat berbagai macam oleh-oleh khas Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/PSP_Pusat_Oleh-Oleh1724375378.webp',
                'color' => '#000000',
                'category_id' => $categoryOlehId,
                'created_at' => '2024-08-23 08:09:39',
                'updated_at' => '2024-08-23 08:10:28',
                'deleted_at' => NULL,
            ),
            array(
                'id' => '65',
                'user_id' => $superAdminId,
                'title' => 'UMKM Center Dekranasda Kota Pontianak',
                'category_id' => $categoryOlehId,
                'description' => 'Pusat oleh-oleh dan produk UMKM Kota Pontianak',
                'url' => NULL,
                'image' => 'uploads/Slider/UMKM_Center_Dekranasda_Kota_Pontianak1724375776.webp',
                'color' => '#000000',
                'created_at' => '2024-08-23 08:16:17',
                'updated_at' => '2024-08-23 08:16:17',
                'deleted_at' => NULL,
            )
        );

        DB::beginTransaction();
        try {
            DB::table('sliders')->insert($sliders);
            DB::commit();
        } catch (\Throwable $th) {
            DB::rollBack();
            throw $th;
        }
    }
}
